apiVersion: v1
kind: Service
metadata:
  name: image-classifier-service
  labels:
    app: image-classifier
spec:
  type: NodePort  # Using NodePort for Minikube access
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
    nodePort: 30080  # Port accessible outside the cluster
  selector:
    app: image-classifier